# Generated by Django 5.1.7 on 2025-04-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('full_open_condition', models.CharField(max_length=100)),
                ('current_condition', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('previous_position', models.CharField(max_length=100)),
            ],
        ),
    ]
