# Generated by Django 5.1.7 on 2025-04-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0002_valve_latitude_valve_location_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='location_link',
        ),
    ]
