# Generated by Django 5.1.7 on 2025-04-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0003_remove_valve_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='location_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
