# Generated by Django 5.1.7 on 2025-04-25 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0004_valve_location_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valve',
            name='location_link',
        ),
        migrations.RemoveField(
            model_name='valve',
            name='location_type',
        ),
        migrations.AddField(
            model_name='valve',
            name='mid_point',
            field=models.FloatField(default=0.5, help_text='Mid-point of the curve (default 0.5).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='valve',
            name='steepness',
            field=models.FloatField(default=12.5, help_text='Steepness factor (default 12.5).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='valve',
            name='current_condition',
            field=models.FloatField(help_text='Enter a number for current condition (e.g., 50.5).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='valve',
            name='full_open_condition',
            field=models.FloatField(help_text='Enter a number for full open condition (e.g., 100.0).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='valve',
            name='previous_position',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
