version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_kwadb
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./backend/.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: kwa_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: backend.settings
    depends_on:
      - mysql
    ports:
      - "6700:8000" # Django Gunicorn exposed at 6700
    volumes:
      - ./backend:/app
      - media_data:/app/media
    networks:
      - app_network

  cms:
    build: ./cms
    container_name: kwa_frontend
    restart: always
    ports:
      - "6701:80" # Frontend served via Nginx at 6701
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  media_data:
