# Generated by Django 5.1.7 on 2025-04-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_permissions_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
