# Generated by Django 5.1.7 on 2025-04-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=255)),
                ('complaint_type', models.CharField(max_length=255)),
                ('ticket_number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area')),
            ],
        ),
    ]
