# Generated by Django 5.1.7 on 2025-04-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='serial_no',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
