# Generated by Django 5.1.7 on 2025-04-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_serial_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('accepted', 'Accepted'), ('processing', 'Processing'), ('return_for_review', 'Return for Review')], default='processing', max_length=20),
        ),
    ]
